services:
  - type: web
    name: daily-task-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        sync: false
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 